In [5]:
import pandas as pd
import random
import numpy as np

# Number of rows
n = 100  

data = {
    'Intersection_ID': [f'INT-{i}' for i in range(1, n+1)],  # Random intersection IDs
    'Time': pd.date_range(start='2024-01-01', periods=n, freq='H'),  # Hourly time series
    'Traffic_Density': np.random.uniform(0, 1, size=n),  # Traffic density as a percentage (0 to 1)
    'Light_Timing': np.random.choice(['Green', 'Yellow', 'Red'], size=n),  # Random light timing
    'Vehicle_Count': np.random.randint(0, 100, size=n),  # Random vehicle count (0 to 100)
}

# Create DataFrame
df = pd.DataFrame(data)

In [27]:
# creating a csv file for this
df.to_csv("Traffic_management_data.csv")

In [6]:
df.head()

,Intersection_ID,Time,Traffic_Density,Light_Timing,Vehicle_Count
0,INT-1,2024-01-01 00:00:00,0.257703,Red,58
1,INT-2,2024-01-01 01:00:00,0.627078,Green,1
2,INT-3,2024-01-01 02:00:00,0.226854,Red,23
3,INT-4,2024-01-01 03:00:00,0.262570,Red,42
4,INT-5,2024-01-01 04:00:00,0.306469,Red,56

In [9]:
df.shape

(100, 5)

In [24]:
df1 = df[df.Intersection_ID == "INT-99"]
df1

,Intersection_ID,Time,Traffic_Density,Light_Timing,Vehicle_Count
98,INT-99,2024-01-05 02:00:00,0.759918,Green,42

In [28]:
df1 = df[df.Light_Timing == "Red"]
df1

,Intersection_ID,Time,Traffic_Density,Light_Timing,Vehicle_Count
0,INT-1,2024-01-01 00:00:00,0.257703,Red,58
2,INT-3,2024-01-01 02:00:00,0.226854,Red,23
3,INT-4,2024-01-01 03:00:00,0.262570,Red,42
4,INT-5,2024-01-01 04:00:00,0.306469,Red,56
5,INT-6,2024-01-01 05:00:00,0.524551,Red,6
11,INT-12,2024-01-01 11:00:00,0.347998,Red,37
12,INT-13,2024-01-01 12:00:00,0.426768,Red,88
14,INT-15,2024-01-01 14:00:00,0.267495,Red,5
16,INT-17,2024-01-01 16:00:00,0.537444,Red,44
18,INT-19,2024-01-01 18:00:00,0.350532,Red,35
19,INT-20,2024-01-01 19:00:00,0.879133,Red,21
21,INT-22,2024-01-01 21:00:00,0.039075,Red,16
24,INT-25,2024-01-02 00:00:00,0.317310,Red,48
31,INT-32,2024-01-02 07:00:00,0.237070,Red,27
33,INT-34,2024-01-02 09:00:00,0.977240,Red,49
34,INT-35,2024-01-02 10:00:00,0.418708,Red,16
36,INT-37,2024-01-02 12:00:00,0.173268,Red,35
37,INT-38,2024-01-02 13:00:00,0.525425,Red,91
38,INT-39,2024-01-02 14:00:00,0.441483,Red,30
39,INT-40,2024-01-02 15:00:00,0.404560,Red,61
44,INT-45,2024-01-02 20:00:00,0.936707,Red,45
45,INT-46,2024-01-02 21:00:00,0.016077,Red,10
51,INT-52,2024-01-03 03:00:00,0.194666,Red,36
52,INT-53,2024-01-03 04:00:00,0.639347,Red,10
55,INT-56,2024-01-03 07:00:00,0.041861,Red,19
58,INT-59,2024-01-03 10:00:00,0.482989,Red,23
59,INT-60,2024-01-03 11:00:00,0.111346,Red,56
67,INT-68,2024-01-03 19:00:00,0.993966,Red,85
68,INT-69,2024-01-03 20:00:00,0.428565,Red,61
69,INT-70,2024-01-03 21:00:00,0.455741,Red,59
74,INT-75,2024-01-04 02:00:00,0.777912,Red,66
76,INT-77,2024-01-04 04:00:00,0.976018,Red,35
79,INT-80,2024-01-04 07:00:00,0.254474,Red,22
84,INT-85,2024-01-04 12:00:00,0.694479,Red,51
85,INT-86,2024-01-04 13:00:00,0.640934,Red,67
87,INT-88,2024-01-04 15:00:00,0.617114,Red,47
91,INT-92,2024-01-04 19:00:00,0.188657,Red,79
92,INT-93,2024-01-04 20:00:00,0.310790,Red,43
93,INT-94,2024-01-04 21:00:00,0.358507,Red,64

In [23]:
for index, row in df1.iterrows():
            density = row['Traffic_Density']
            if density > 0.7:
                df.at[index, 'Light_Timing'] = 'Green'
            elif 0.3 < density <= 0.7:
                df.at[index, 'Light_Timing'] = 'Yellow'
            else:
                df.at[index, 'Light_Timing'] = 'Red'

In [25]:
df1 = df[df.Intersection_ID == "INT-99"]
df1

,Intersection_ID,Time,Traffic_Density,Light_Timing,Vehicle_Count
98,INT-99,2024-01-05 02:00:00,0.759918,Green,42

In [26]:
import pandas as pd
import numpy as np

class TrafficManager:
    def __init__(self, df):
        self.df = df

    def adjust_light_timings(self, intersection_id):
        intersection_data = self.df[self.df['Intersection_ID'] == intersection_id].copy()
        
        # Adjust light timings based on traffic density
        for index, row in intersection_data.iterrows():
            density = row['Traffic_Density']
            if density > 0.7:
                self.df.at[index, 'Light_Timing'] = 'Green'
            elif 0.3 < density <= 0.7:
                self.df.at[index, 'Light_Timing'] = 'Yellow'
            else:
                self.df.at[index, 'Light_Timing'] = 'Red'

    def simulate_traffic_flow(self, intersection_id):
        intersection_data = self.df[self.df['Intersection_ID'] == intersection_id].copy()
        
        for index, row in intersection_data.iterrows():
            vehicle_count = row['Vehicle_Count']
            light_timing = row['Light_Timing']
            
            if light_timing == 'Green':
                vehicles_passed = min(vehicle_count, 60)  # Green light allows up to 60 vehicles
            elif light_timing == 'Yellow':
                vehicles_passed = min(vehicle_count, 20)  # Yellow allows fewer vehicles
            else:
                vehicles_passed = 0  # No vehicles pass on red
            
            print(f"Intersection {intersection_id} at {row['Time']}: {vehicles_passed} vehicles passed during {light_timing} light.")

    def optimize_and_simulate(self, intersection_id):
        self.adjust_light_timings(intersection_id)
        self.simulate_traffic_flow(intersection_id)


traffic_manager = TrafficManager(df)
traffic_manager.optimize_and_simulate('INT-99')

Intersection INT-99 at 2024-01-05 02:00:00: 42 vehicles passed during Green light.